spring.application.name=harmonia-api


# ===============================================================
# CONFIGURAÇÕES DO BANCO DE DADOS (POSTGRESQL)
# ===============================================================
spring.datasource.url=${URL_DATABASE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================================================
# CONFIGURAÇÕES DO HIKARI CONNECTION POOL
# ===============================================================
# Máximo de conexões no pool
spring.datasource.hikari.maximum-pool-size=10

# Mínimo de conexões ociosas mantidas no pool
spring.datasource.hikari.minimum-idle=5

# Tempo máximo (em ms) que uma conexão pode viver antes de ser reciclada
# 10 minutos = 600000 ms (evita conexões stale fechadas pelo banco)
spring.datasource.hikari.max-lifetime=600000

# Tempo máximo (em ms) para obter uma conexão do pool
spring.datasource.hikari.connection-timeout=30000

# Tempo máximo (em ms) que uma conexão pode ficar ociosa antes de ser fechada
spring.datasource.hikari.idle-timeout=600000

# ===============================================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================================================
# Define a estratégia de criação/atualização das tabelas no banco
spring.jpa.hibernate.ddl-auto=update

# Mostra as queries SQL geradas pelo Hibernate no console (ótimo para desenvolvimento)
spring.jpa.show-sql=true

# Formata o SQL no console para ficar legível, em vez de uma linha única gigante
spring.jpa.properties.hibernate.format_sql=true

# Configura o dialeto do PostgreSQL para o Hibernate otimizar os recursos nativos do banco
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

