spring.application.name=harmonia-api

# ===============================================================
# CONFIGURAÇÕES DO BANCO DE DADOS (POSTGRESQL)
# ===============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/harmonia
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================================================
# Define a estratégia de criação/atualização das tabelas no banco
spring.jpa.hibernate.ddl-auto=update

# Mostra as queries SQL geradas pelo Hibernate no console (ótimo para desenvolvimento)
spring.jpa.show-sql=true

# Formata o SQL no console para ficar legível, em vez de uma linha única gigante
spring.jpa.properties.hibernate.format_sql=true

# Configura o dialeto do PostgreSQL para o Hibernate otimizar os recursos nativos do banco
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
